### ISSUE TITLE
Not having to say "ask"

### ISSUE THREAD

**Issue by nospam2k** [awilhelmer/alexa-mqtt-skill#1]
Is there a way to implement this skill (as with other "Smart" skills) without having to say "ask"? If so can you provide the necessary code modification? I just want to be able to say "Alexa, set the whatever to 60%"

**Comment by awilhelmer** [comment]
This is an ask schema skill. You have the option to choose between an ask skill and a smart home skill. You can migrate this project to a smart skill.

https://developer.amazon.com/docs/smarthome/understand-the-smart-home-skill-api.html
https://developer.amazon.com/docs/smarthome/authenticate-an-alexa-user-account-linking.html

The Smart Home skill needs an account linking via Oauth 2, so the skill must handle different users (or only one static user - yourself in this case). Here is some work to do, but yes it is possible. I didn't find any example skill to follow up. 

The second step is to simulate all possible devices configured in this skill and parse all command messages from alexa with their device api. Or only one device, that can do everything (the device list in the alexa app)? 

BTW, you can also use"say", e.g. "Alexa, say broker kitchen light on"

**Comment by nospam2k** [comment]
Thanks for that info. I have discovered much of what you said since my post but I appreciate your response!
